app:
  jwt:
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
    expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: POSTGRESQL

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: task_tracker
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /index.html
#    operations-sorter: method
#    tags-sorter: alpha
#    enabled: true
#    disable-swagger-default-url: true

logging:
  level:
    root: INFO
    com:
      vay:
        tasktracker: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
#  sql:
#    init:
#      mode: always